### ISSUE TITLE
Mirroring takes up too much space

### ISSUE THREAD

**Issue by Container-Zero** [Melanpan/wd-tagger-docker#1]
The build image seems to download the entire `huggingface/transformers-pytorch-gpu:4.29.2` image, which results in a total hard disk usage of up to `16.51GB`. This is far too large for most cloud servers.
If I just want to use the `swinv2` model of `wd-tagger` and take out the GPU acceleration, can I reduce the amount of hard disk capacity consumed by the mirrors, e.g. keep the total final capacity footprint under `2GB`?

**Comment by Melanpan** [comment]
That should be possible, the `huggingface/transformers-pytorch-gpu:4.29.2` base imagine isn't a hard requirement and it probably would work just as well with `debian:latest` although I haven't tested this yet.

**Comment by Container-Zero** [comment]
> 这应该是可能的，`huggingface/transformers-pytorch-gpu:4.29.2`基本想象不是一个硬性要求，它可能会工作得很好，`debian:latest`尽管我还没有测试过。

Thanks for the reply, I don't really understand how docker is built i.e. how it works, and I know very little about wd-tagger.
I tried to use `huggingface/transformers-pytorch-cpu` but this seems to have failed.
Can you suggest some modifications specific to the current project to reduce the size of the mirroring file's capacity footprint?
Or if you don't mind, could you release a version with a smaller footprint that is easier to use on low performance servers? Thank you very much.

**Comment by Melanpan** [comment]
I've made some changes, you should be able to use the `Dockerfile-nocuda` file now and it will build a debian 12-slim image so there is no  need to pull the entire `huggingface/transformers-pytorch-gpu` image anymore if you don't need cuda acceleration.

**Comment by Container-Zero** [comment]
> I've made some changes, you should be able to use the `Dockerfile-nocuda` file now and it will build a debian 12-slim image so there is no need to pull the entire `huggingface/transformers-pytorch-gpu` image anymore if you don't need cuda acceleration.

Thank you very much for providing a solution optimized for disk footprint, it is appreciated! I tried the new deployment method the first time I saw it.
The compile to mirroring process went smoothly, and the whole process used roughly the following commands.
```
git clone https://github.com/Melanpan/wd-tagger-docker.git
cp Dockerfile-nocuda Dockerfile
docker build -t wdtagger .
docker run --rm -p 8005:8000 wdtagger
```

However, I seem to be running into some problems when starting the image, roughly as follows:

```
docker run --rm -p 8005:8000 wdtagger

[2023-10-15 16:25:33 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-10-15 16:25:33 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2023-10-15 16:25:33 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-10-15 16:25:33 +0000] [6] [INFO] Booting worker with pid: 6
INFO:wd_tagger:Loading model
model.onnx: 100%|██████████| 455M/455M [00:05<00:00, 84.3MB/s] 
INFO:wd_tagger:Model path: /tmp/model_cache/model.onnx, providers: ['CUDAExecutionProvider']
/usr/local/lib/python3.11/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
[2023-10-15 16:25:44 +0000] [1] [WARNING] Worker with pid 6 was terminated due to signal 9c
......
```
It seems to still be trying to call CUDA to do the calculations?The project doesn't seem to be working properly, it keeps repeating the above error indefinitely, and port 8005 doesn't seem to be responding properly.I'm not sure if I'm doing something wrong?

**Comment by Melanpan** [comment]
That was a mistake on my part, it defaults to trying to use CUDA. If it doesn't see that the env variable USE_CUDA is defined it defaults to using it. 

A solution for that would be `docker run --rm -p 8005:8000 -e USE_CUDA=0 wdtagger`
However, I changed the code to default to not using cuda, if you would like to rebuild it.

**Comment by Container-Zero** [comment]
> That was a mistake on my part, it defaults to trying to use CUDA. If it doesn't see that the env variable USE_CUDA is defined it defaults to using it.
> 
> A solution for that would be `docker run --rm -p 8005:8000 -e USE_CUDA=0 wdtagger` However, I changed the code to default to not using cuda, if you would like to rebuild it.

Thank you very much, everything is working properly from now on!

There may also be two other points of information that may be useful for this project:
1. `DockerFile` in `cp Dockerfile-nocuda DockerFile` in the `readme.md` file should be `Dockerfile` (`F` lowercase). Otherwise it will report error `unable to prepare context: unable to evaluate symlinks in Dockerfile`.
2. If infinite returns `[WARNING] Worker with pid [a certain number] was terminated due to signal [another number]` .... The probability is that the current server is running out of memory.

Perhaps if you change or add information such as the above in the readme, it could help people use the program more easily?

Another thing is that this project is not directly committed to the docker repository, is it because for some reason it has to be compiled locally and can't be downloaded and launched as a pull?

Anyway thank you very much for your outstanding project!
